# This is a basic workflow to help you get started with Actions

name: Bing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ main ]
#    paths:
#    - '!.github/workflows/**'
  schedule:
    - cron: "0 17 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Fetch-and-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out taskbot
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: ScienisTmiaoT/taskbot
          token: ${{ secrets.PAT }}
          path: taskbot  
      - name: Check out photogallery
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: ScienisTmiaoT/photogallery
          token: ${{ secrets.PAT }}
          path: photogallery   
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.0' #install the python needed
          cache: 'pip'
      - name: install dependencies
        working-directory: ./taskbot
        run: |
          pip install -r ./bing/requirements.txt # export dependencies: pip freeze > requirements.txt
      - name: Set env for python script
        run: |
          echo "script=bing" >> $GITHUB_ENV
          echo "prod=Y" >> $GITHUB_ENV
          echo "root_path=bing" >> $GITHUB_ENV
      - name: execute py script # run the .py to generate the latest data
        working-directory: ./taskbot
        run: |
          python ./main.py
      - if: env.GOOD_TO_PUBLISH == 'Y'
        working-directory: ./taskbot
        run: |
          git add .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "push update for bing"
          git push  
      - if: env.GOOD_TO_PUBLISH == 'Y'
        name: Push data.js
        working-directory: ./photogallery
        run: |
          git add .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "update photo"
          git push  
