name: Keepalive
on:
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch:
jobs:
  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - uses: gautamkrishnar/keepalive-workflow@v2
