name: git-mirror

on:
  workflow_dispatch:
  
jobs:
  Fetch-and-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out from dataset 
        uses: actions/checkout@v4
        with:
          ref: stockanalyzer
          repository: ScienisTmiaoT/stock-dataset-v2
          token: ${{ secrets.PAT }}
          path: stock-dataset-v2 
      - name: Check out to dataset
        uses: actions/checkout@v4
        with:
          ref: stockanalyzer
          repository: ScienisTmiaoT/stock-dataset
          token: ${{ secrets.PAT }}
          path: stock-dataset 
      - name: mirror dataset
        working-directory: ./stock-dataset
        run: |
          rm -rf ../stock-dataset-v2/data/comment
          cp -R ../stock-dataset-v2/data .
          git add .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "migrate stock-dataset"
          git push 
