name: Poptags

on:
  schedule:
    - cron: "0/10 * * * *"

  workflow_dispatch:

jobs:
  Fetch-and-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out taskbot
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: ScienisTmiaoT/taskbot
          token: ${{ secrets.PAT }}
          path: taskbot  
      - name: Check out poptags
        uses: actions/checkout@v3
        with:
          ref: main
          repository: ScienisTmiaoT/poptags
          token: ${{ secrets.PAT }}
          path: poptags   
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' #install the python needed
          cache: 'pip'
      - name: install dependencies
        working-directory: ./taskbot
        run: |
          pip install -r ./twitter/requirements.txt # export dependencies: pip freeze > requirements.txt
      - name: Set env for python script
        run: |
          echo "script=twitter" >> $GITHUB_ENV
          echo "prod=Y" >> $GITHUB_ENV
          echo "root_path=twitter" >> $GITHUB_ENV
      - name: execute py script # run the .py to generate the latest data
        working-directory: ./taskbot
        run: |
          python main.py
      - if: env.GOOD_TO_PUBLISH == 'Y'
        name: Push poptags
        working-directory: ./poptags
        run: |
          git add .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "update poptags"
          git push  
