# This is a basic workflow to help you get started with Actions

name: Weibo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ main ]
#    paths:
#    - '!.github/workflows/**'
  schedule:
    - cron: "0 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Fetch-and-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out script
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: ScienisTmiaoT/weibo-crawler
          token: ${{ secrets.PAT }}
          path: weibo
      - name: Check out popwords
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: ScienisTmiaoT/popwords
          token: ${{ secrets.PAT }}
          path: popwords
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' #install the python needed
          cache: 'pip'
      - name: install dependencies
        working-directory: ./weibo
        run: |
          pip install -r ./requirements.txt # export dependencies: pip freeze > requirements.txt
      - name: Set env for python script
        run: |
          echo "topic_page_num=100" >> $GITHUB_ENV
          echo "hot_words_top_k=100" >> $GITHUB_ENV
          echo "sleep_low=1" >> $GITHUB_ENV
          echo "sleep_high=3" >> $GITHUB_ENV     
      - name: execute py script # run the .py to generate the latest data
        working-directory: ./weibo
        run: |
          python ./weibo.py
      - name: Push update
        working-directory: ./weibo
        run: |
          git add .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "push update for weibo crawler"
          git push  
      - if: env.GOOD_TO_PUBLISH == 'Y'
        name: Push data.js
        working-directory: ./popwords
        run: |
          git add .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "push data.js"
          git push  
